# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path: ~
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"


    filter_sets:
        cache: ~
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [ 210, 118 ], mode: outbound }

        mini_thumbs:
            quality: 75
            filters:
                thumbnail: { size: [ 120, 76 ], mode: outbound }

        garderie_thumbs:
            quality: 75
            filters:
                thumbnail: { size: [ 300, 200 ], mode: outbound }

        article_creation_preview:
            quality: 75
            filters:
                thumbnail: { size: [ 360, 230 ], mode: outbound }

        mini_portrait_thumbs:
            quality: 75
            filters:
                thumbnail: { size: [ 50, 50 ], mode: outbound }

        portrait_thumbs:
            quality: 75
            filters:
                thumbnail: { size: [ 120, 76 ], mode: outbound }