# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"


    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [ 210, 118 ], mode: outbound }

        garderie_thumbs:
            quality: 75
            filters:
                thumbnail: { size: [ 300, 200 ], mode: outbound }
                background: { size : [304, 104], position : center, color : '#ffffff' }