vich_uploader:
    db_driver: orm

    mappings:
        home_page_image:
            uri_prefix: /images/content/home_page
            upload_destination: '%kernel.project_dir%/public/images/content/home_page'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        basic_page_banner_image:
            uri_prefix: /images/content/basic_page
            upload_destination: '%kernel.project_dir%/public/images/content/basic_page'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        article_image:
            uri_prefix: /images/content/article
            upload_destination: '%kernel.project_dir%/public/images/content/article'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
